version: "3"

services:
  arddev:
    build: .
    environment:
      - LOGLEVEL=ERROR
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/dataprep