version: "3"

services:
  arddev:
    build: .
    environment:
      - LOGLEVEL=ERROR
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - COPERNICUS_USERNAME=${COPERNICUS_USERNAME}
      - COPERNICUS_PWD=${COPERNICUS_PWD}
    ports:
      - "8885:8885"
    volumes:
      - ../../../data:/tmp/data
      - ../../../ard-workflows:/opt/notebooks
